config/routes.rb
Rails.application.routes.draw do
  root to: "materials#index"
  devise_for :users
  resources :materials, except: [:edit]
  get "materials/:id/entrada", to: 'materials#entrada', as: 'material_entrada', action: 'entrada'
  get "materials/:id/saida", to: 'materials#saida', as: 'material_saida' , action: 'saida'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :material
  belongs_to :user

end

app/models/material.rb
class Material < ApplicationRecord
  validates :name, uniqueness: true
  validates :quantify, presence: true
  validates :quantify, :numericality => { :greater_than_or_equal_to => 0 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :set_material, only: [:show, :entrada, :saida, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/entrada
  def entrada
  end

  # GET /materials/1/saida
  def saida
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)
    if @material.save
      redirect_to @material
      flash[:notice] = 'Material foi criado.'
    else
      render :new
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    if hour_block == true
      if quantify_can_be_bigger == true && params[:type] == "entrada"
        entrada_and_saida_update
      elsif quantify_can_be_bigger == false && params[:type] == "saida"
        entrada_and_saida_update
      else
        flash[:notice] = 'Material não foi atualizado.'
      end
    else
      flash[:notice] = 'Material só pode ser atualizada entre ás 9 e as 19 horas.'

    end
  end

  private
    def entrada_and_saida_update
      if @material.update(material_params)
        flash[:notice] = 'Material foi atualizado.'
        redirect_to @material
      else
        flash[:notice] = 'Material não foi atualizado.'
        render :edit
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def hour_block
      t = Time.zone.now
      if t.hour < 18 && t.hour > 9
        return true
      else
        return false
      end
    end

    def quantify_can_be_bigger
      @params = material_params
      name = @params[:name]
      @material = Material.find_by(name: name)
      if @params[:quantify].present? && @material != nil
        valueNew = @params[:quantify].to_i
        valueOld =  @material.quantify.to_i
        if valueNew > valueOld
          return true
        else
          return false
        end
      end
    end

    def set_material
      @material = Material.find(params[:id])
    end

    def material_params
      params.require(:material).permit(:name, :quantify)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geri</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col s6 push-s3">

      <div class="input-field ">
        <%= form.label :name %>
        <%= form.text_field :name, id: :material_name %>
      </div>

      <div class="input-field">
        <%= form.label :quantify %>
        <%= form.text_field :quantify, id: :material_quantify%>
      </div>

      <div class="input-field ">
        <%= form.submit 'Enviar', :class => 'btn btn-inverse' %>
      </div>
  </div>
</div>

<% end %>

app/views/materials/_form_entrada.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col s6 push-s3">
      <%= hidden_field_tag "type", "entrada" %>

      <div class="input-field ">
        <%= form.label :name %>
        <%= form.text_field :name, id: :material_name %>
      </div>

      <div class="input-field">
        <%= form.label :quantify %>
        <%= form.text_field :quantify, id: :material_quantify%>
      </div>

      <div class="input-field ">
        <%= form.submit 'Enviar', :class => 'btn btn-inverse' %>
      </div>
  </div>
</div>

<% end %>

app/views/materials/_form_saida.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row">
  <div class="col s6 push-s3">
      <%= hidden_field_tag "type", "saida" %>

      <div class="input-field ">
        <%= form.label :name %>
        <%= form.text_field :name, id: :material_name %>
      </div>

      <div class="input-field">
        <%= form.label :quantify %>
        <%= form.text_field :quantify, id: :material_quantify%>
      </div>

      <div class="input-field ">
        <%= form.submit 'Enviar', :class => 'btn btn-inverse' %>
      </div>
  </div>
</div>

<% end %>

app/views/materials/edit.html.erb
<h1 class="center">Editar Material</h1>
<div class="row">
  <div class="col s3 push-s8">
    <%= link_to 'Voltar', materials_path , :class => 'waves-effect waves-light btn' %>
  </div>
</div>

<%= render 'form', material: @material %>

app/views/materials/entrada.html.erb
<h1 class="center">Entrada de Material</h1>
<p class="notice center"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="row">
  <div class="col s3 push-s8">
    <%= link_to 'Voltar', materials_path , :class => 'waves-effect waves-light btn' %>
  </div>
</div>

<%= render 'form_entrada', material: @material %>

app/views/materials/index.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<h1 class="center">Materials</h1>

<div class="row">
  <div class="col s6 push-s3">
    <table>
  <thead>
    <tr>
      <th>Material</th>
      <th>Quantidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.quantify %></td>
        <td><%= link_to 'Ver Material', material %></td>
        <td><%= link_to 'Entrada de material', material_entrada_path(material.id) %></td>
        <td><%= link_to 'Saida de material', material_saida_path(material.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
  </div>
</div>

<br>

<div class="row">
  <div class="col s3 push-s3">
    <%= link_to 'Novo Material', new_material_path, :class => "btn btn-inverse" %>
  </div>
</div>

app/views/materials/new.html.erb
<h1>Novo Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Voltar', materials_path %>

app/views/materials/saida.html.erb
<h1 class="center">Saida de  Material</h1>
<p class="notice center"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div class="row">
  <div class="col s3 push-s8">
    <%= link_to 'Voltar', materials_path , :class => 'waves-effect waves-light btn' %>
  </div>
</div>

<%= render 'form_saida', material: @material %>

app/views/materials/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col s3 push-s3">
    <div class="card teal lighten-2">
      <div class="card-content">
        <span class="card-title white-text">Material : <%= @material.name %></span>
        <span class="white-text">Quantidade: <%= @material.quantify %></span>
    </div>
  </div>
  </div>
</div>

<div class="row">
  <div class="col s3 push-s3">
    <%= link_to 'Voltar', materials_path, :class => 'waves-effect waves-light btn' %>
  </div>
</div>